### PR TITLE
Java 11 compatible compilation

### PR DESCRIPTION
**Pull request by markrekveld**
My attempt at #1

### CODE REVIEW

**Comment by CarlAmko** [comment]
Thanks for the PR @markrekveld. 

We have an internal effort on the roadmap to determine which JDK versions we can support and how to best facilitate them to end users. Stay posted!

**Comment by markrekveld** [comment]
@Wonderful-Space good news, but do you have any time window in which the decision will be made.

**Comment by CarlAmko** [comment]
Hi @markrekveld,
I’m investigating support for JDK 11, but I’m seeing some breaking changes since we are using newer language constructs and API features from Java 17. We’ll get back to you on a timeline tomorrow.

**Comment by nijikokun** [comment]
> @Wonderful-Space good news, but do you have any time window in which the decision will be made.

Hey Mark, thanks for the PR! 

I'm going to go ahead and close this PR since it looks like work is happening over in #12. 

Feel free to check it out and follow along / give input!

**Comment by nijikokun** [comment]
Just following up on this thread @markrekveld looks like #12 has landed and now Java 11 is supported 🎉

**Comment by markrekveld** [comment]
Thanks @nijikokun  and ngrok team!

**Pull request closed without merging**
